/// <File> FileName.cs </File>
/// <FileDesc>
/// 
/// </FileDesc>
/// <History>
///	<Devoloper> Shao Chen Ye </Devoloper>
///	<Date> 2004-11-06  </ChangeDate>
///     <Description> </Description>
/// </History>

/*********** references and namespaces  ***************/
using System;


namespace Alivever.Com.DevBasic.BasicLib.DbCtrl
{
	/// <summary>
	/// interface IDbObjSql. 
	/// </summary>
	/// <History>
	///	<Devoloper> Shao Chen Ye </Devoloper>
	///	<Date> 2004-11-06  </ChangeDate>
	///     <Description>Create interface </Description>
	/// </History>
	public interface IDbObjSql 
	{

		// =========== methods ================
		/// <summary>
		/// Initializor 
		/// </summary>
		string GetTableName() ;

		/// <summary>
		/// Return keys names. Such as: "UsrID, RecordTime"
		/// Note: DbAutoKey here means the primary ket that can be 
		///       auto-generated by DB when Insert.
		/// </summary>
		string GetDbAutoKeyNameStr() ;

		/// <summary>
		/// Return keys values. Such as: "'0000001', '2004-11-16'"
		/// This function will be used by SQL Insert command
		/// Note: DbAutoKey here means the primary ket that can be 
		/// </summary>
		string GetDbAutoKeyValueStr() ;

		/// <summary>
		/// Return keys names. Such as: "UsrID, RecordTime"
		/// Note: NotNullCols here mean not NULL Columns except DbAutoKey
		/// </summary>
		string GetNotNullColsNameStr() ;

		/// <summary>
		/// Return keys values. Such as: "'0000001', '2004-11-16'"
		/// This function will be used by SQL Insert command
		/// Note: 1. NotNullCols here mean not NULL Columns except DbAutoKey
		///       2. the order of columns must be as same as GetNotNullColsNameStr().
		/// </summary>
		string GetNotNullColsValueStr() ;

		/// <summary>
		/// Return NormalColumn names. Such as: "RecordAttrib1, RecordDesc"
		/// Note: NormalColumn here means Columns except NotNullCols.
		/// </summary>
		string GetNormalColNameStr();
		
		/// <summary>
		/// Return NormalColumn values. Such as: "'fsdafs', 'hrtrrt'"
		/// Note: 1. NormalColumn here means Columns except NotNullCols.
		///       2. the order of columns must be as same as GetNormalColNameStr().
		/// </summary>
		string GetNormalColValueStr();
		
	} //interface IDbDftObjAccess 

}//namespace
